const key = 'price-watch-items-v1';
const deliveryLocation = 'Ростов-на-Дону';
let items = JSON.parse(localStorage.getItem(key) || 'null') || [{ id: 1, name: 'Xiaomi Redmi Note 14 8/256', price: 19990, oldPrice: 21490, limit: 20000, region: deliveryLocation, inStock: true, paused: false, notifyStock: true, notifyPrice: true, notifyDrops: false }];
let screen = 'list'; let editing = null;
const app = document.querySelector('#app'); const toast = document.querySelector('#toast');
const money = n => new Intl.NumberFormat('ru-RU').format(n) + ' ₽';
const save = () => localStorage.setItem(key, JSON.stringify(items));
function notify(text) { toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3300); }
function productCard(p) { return `<article class="product-card"><div class="product-top"><div class="product-img">📱</div><div><div class="product-name">${p.name}</div><div class="price">${money(p.price)}</div><div class="old-price">${money(p.oldPrice)}</div><div class="chip ${p.inStock ? 'good' : 'none'}">${p.inStock ? 'В наличии' : 'Нет в наличии'}</div><div class="threshold">Порог: ≤ ${money(p.limit)}</div></div><button class="menu" onclick="editItem(${p.id})" aria-label="Настроить">⋮</button></div><div class="actions"><button class="action" onclick="togglePause(${p.id})">${p.paused ? '▶ Возобновить' : 'Ⅱ Приостановить'}</button><button class="action delete" onclick="removeItem(${p.id})">🗑 Удалить</button></div></article>`; }
function renderList() { app.innerHTML = `<div class="topline"><span>Цена под контролем</span><button class="icon-btn" onclick="requestPush()">⚙</button></div><h1>Мои товары</h1><p class="count">${items.length} ${items.length === 1 ? 'товар' : 'товара'} · ${deliveryLocation}</p>${items.length ? items.map(productCard).join('') : '<div class="empty">Нет отслеживаемых товаров.<br>Добавьте первый товар по названию или ссылке.</div>'}<button class="fab" onclick="newItem()" aria-label="Добавить товар">+</button>`; }
function renderForm(p) { app.innerHTML = `<div class="screen-head"><button class="icon-btn" onclick="goList()">‹</button><h1>Отслеживание товара</h1></div><div class="product-mini"><div class="product-img">📱</div><div><p>${p.name}</p><strong>${money(p.price)}</strong><span class="old-price">${money(p.oldPrice)}</span></div></div><p class="hint">Доставка: ${deliveryLocation}</p><label class="form-label" for="name">Название или ссылка</label><input class="field" id="name" value="${p.name}"><label class="form-label" for="limit">Максимальная цена покупки</label><input class="field" id="limit" inputmode="numeric" type="number" min="1" value="${p.limit}"><p class="hint">Уведомить, если цена равна или ниже этой суммы</p><section class="settings-group"><label class="switch-row"><span>Появился в наличии</span><input class="switch" id="notifyStock" type="checkbox" ${p.notifyStock?'checked':''}></label><label class="switch-row"><span>Цена стала ниже порога</span><input class="switch" id="notifyPrice" type="checkbox" ${p.notifyPrice?'checked':''}></label><label class="switch-row"><span>Уведомлять о каждом снижении</span><input class="switch" id="notifyDrops" type="checkbox" ${p.notifyDrops?'checked':''}></label></section><button class="primary" onclick="saveForm(${p.id})">${p.id ? 'Сохранить изменения' : 'Начать отслеживание'}</button>`; }
function newItem(){ editing = {id:0,name:'Новый товар',price:0,oldPrice:0,limit:10000,region:deliveryLocation,inStock:false,notifyStock:true,notifyPrice:true,notifyDrops:false}; screen='form'; render(); }
function editItem(id){ editing = {...items.find(x=>x.id===id)}; screen='form'; render(); }
function saveForm(id){ const name=document.querySelector('#name').value.trim(), limit=Number(document.querySelector('#limit').value); if(!name || !limit){ notify('Введите название и максимальную цену'); return; } const values={...editing,id:id||Date.now(),name,limit,region:deliveryLocation,notifyStock:document.querySelector('#notifyStock').checked,notifyPrice:document.querySelector('#notifyPrice').checked,notifyDrops:document.querySelector('#notifyDrops').checked}; if(!id){ values.price=0; values.oldPrice=0; values.inStock=false; items.unshift(values); } else items=items.map(x=>x.id===id?values:x); save(); goList(); notify('Отслеживание сохранено'); }
function togglePause(id){ items=items.map(x=>x.id===id?{...x,paused:!x.paused}:x); save(); render(); }
function removeItem(id){ items=items.filter(x=>x.id!==id); save(); render(); notify('Товар удалён'); }
function goList(){screen='list'; editing=null; render();} function render(){screen==='list'?renderList():renderForm(editing);}
async function requestPush(){ if(!('Notification' in window)){notify('Push не поддерживаются в этом браузере');return;} const result=await Notification.requestPermission(); notify(result==='granted'?'Push-уведомления включены':'Разрешение на уведомления не выдано'); }
window.newItem=newItem; window.editItem=editItem; window.saveForm=saveForm; window.togglePause=togglePause; window.removeItem=removeItem; window.goList=goList; window.requestPush=requestPush;
render();
